
on:
  push:
    branches:
      - master






jobs:
  build:
    runs-on: ubunty-latest

    steps:
      - name: 'Testing github action'
        run: pwd

      - name: 'testing printing'
        run: echo AboMera